/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.ColumnNameEntry;
import com.liferay.portal.tools.service.builder.test.service.ColumnNameEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.ColumnNameEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.ColumnNameEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the column name entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.ColumnNameEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.ColumnNameEntryLocalServiceImpl
 * @generated
 */
public abstract class ColumnNameEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements ColumnNameEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ColumnNameEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ColumnNameEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the column name entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ColumnNameEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param columnNameEntry the column name entry
	 * @return the column name entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ColumnNameEntry addColumnNameEntry(ColumnNameEntry columnNameEntry) {
		columnNameEntry.setNew(true);

		return columnNameEntryPersistence.update(columnNameEntry);
	}

	/**
	 * Creates a new column name entry with the primary key. Does not add the column name entry to the database.
	 *
	 * @param columnNameEntryId the primary key for the new column name entry
	 * @return the new column name entry
	 */
	@Override
	@Transactional(enabled = false)
	public ColumnNameEntry createColumnNameEntry(long columnNameEntryId) {
		return columnNameEntryPersistence.create(columnNameEntryId);
	}

	/**
	 * Deletes the column name entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ColumnNameEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param columnNameEntryId the primary key of the column name entry
	 * @return the column name entry that was removed
	 * @throws PortalException if a column name entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ColumnNameEntry deleteColumnNameEntry(long columnNameEntryId)
		throws PortalException {

		return columnNameEntryPersistence.remove(columnNameEntryId);
	}

	/**
	 * Deletes the column name entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ColumnNameEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param columnNameEntry the column name entry
	 * @return the column name entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ColumnNameEntry deleteColumnNameEntry(
		ColumnNameEntry columnNameEntry) {

		return columnNameEntryPersistence.remove(columnNameEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return columnNameEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ColumnNameEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return columnNameEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.ColumnNameEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return columnNameEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.ColumnNameEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return columnNameEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return columnNameEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return columnNameEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ColumnNameEntry fetchColumnNameEntry(long columnNameEntryId) {
		return columnNameEntryPersistence.fetchByPrimaryKey(columnNameEntryId);
	}

	/**
	 * Returns the column name entry with the primary key.
	 *
	 * @param columnNameEntryId the primary key of the column name entry
	 * @return the column name entry
	 * @throws PortalException if a column name entry with the primary key could not be found
	 */
	@Override
	public ColumnNameEntry getColumnNameEntry(long columnNameEntryId)
		throws PortalException {

		return columnNameEntryPersistence.findByPrimaryKey(columnNameEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(columnNameEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ColumnNameEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("columnNameEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			columnNameEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ColumnNameEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"columnNameEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(columnNameEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ColumnNameEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("columnNameEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return columnNameEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement ColumnNameEntryLocalServiceImpl#deleteColumnNameEntry(ColumnNameEntry) to avoid orphaned data");
		}

		return columnNameEntryLocalService.deleteColumnNameEntry(
			(ColumnNameEntry)persistedModel);
	}

	@Override
	public BasePersistence<ColumnNameEntry> getBasePersistence() {
		return columnNameEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return columnNameEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the column name entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.ColumnNameEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of column name entries
	 * @param end the upper bound of the range of column name entries (not inclusive)
	 * @return the range of column name entries
	 */
	@Override
	public List<ColumnNameEntry> getColumnNameEntries(int start, int end) {
		return columnNameEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of column name entries.
	 *
	 * @return the number of column name entries
	 */
	@Override
	public int getColumnNameEntriesCount() {
		return columnNameEntryPersistence.countAll();
	}

	/**
	 * Updates the column name entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ColumnNameEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param columnNameEntry the column name entry
	 * @return the column name entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ColumnNameEntry updateColumnNameEntry(
		ColumnNameEntry columnNameEntry) {

		return columnNameEntryPersistence.update(columnNameEntry);
	}

	/**
	 * Returns the column name entry local service.
	 *
	 * @return the column name entry local service
	 */
	public ColumnNameEntryLocalService getColumnNameEntryLocalService() {
		return columnNameEntryLocalService;
	}

	/**
	 * Sets the column name entry local service.
	 *
	 * @param columnNameEntryLocalService the column name entry local service
	 */
	public void setColumnNameEntryLocalService(
		ColumnNameEntryLocalService columnNameEntryLocalService) {

		this.columnNameEntryLocalService = columnNameEntryLocalService;
	}

	/**
	 * Returns the column name entry persistence.
	 *
	 * @return the column name entry persistence
	 */
	public ColumnNameEntryPersistence getColumnNameEntryPersistence() {
		return columnNameEntryPersistence;
	}

	/**
	 * Sets the column name entry persistence.
	 *
	 * @param columnNameEntryPersistence the column name entry persistence
	 */
	public void setColumnNameEntryPersistence(
		ColumnNameEntryPersistence columnNameEntryPersistence) {

		this.columnNameEntryPersistence = columnNameEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		ColumnNameEntryLocalServiceUtil.setService(columnNameEntryLocalService);
	}

	public void destroy() {
		ColumnNameEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ColumnNameEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ColumnNameEntry.class;
	}

	protected String getModelClassName() {
		return ColumnNameEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = columnNameEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = ColumnNameEntryLocalService.class)
	protected ColumnNameEntryLocalService columnNameEntryLocalService;

	@BeanReference(type = ColumnNameEntryPersistence.class)
	protected ColumnNameEntryPersistence columnNameEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ColumnNameEntryLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:643511781