dependencies {
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-cbor", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-smile", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-xml", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-yaml", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.datatype", name: "jackson-datatype-jdk8", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.datatype", name: "jackson-datatype-jsr310", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.jaxrs", name: "jackson-jaxrs-base", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.jaxrs", name: "jackson-jaxrs-json-provider", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.jaxrs", name: "jackson-jaxrs-xml-provider", version: "2.16.1"
	compileInclude group: "com.fasterxml.jackson.module", name: "jackson-module-jaxb-annotations", version: "2.16.1"
	compileInclude group: "org.yaml", name: "snakeyaml", version: "2.0"
}