dependencies {
	compileOnly group: "org.apache.geronimo.specs", name: "geronimo-jaxrs_2.1_spec", version: "1.1"
	compileOnly group: "org.apache.geronimo.specs", name: "geronimo-json_1.1_spec", version: "1.5"
	compileOnly group: "org.apache.geronimo.specs", name: "geronimo-jsonb_1.0_spec", version: "1.4"
}

deployDependencies {
	from configurations.compileOnly

	include "geronimo-jsonb_1.0_spec-*.jar"
	rename(/geronimo-jsonb_1\.0_spec-(.+)\.jar/, "geronimo-jsonb_1.0_spec" + renameSuffix)

	include "geronimo-jaxrs_2.1_spec-*.jar"
	rename(/geronimo-jaxrs_2\.1_spec-(.+)\.jar/, "geronimo-jaxrs_2.1_spec" + renameSuffix)

}