dependencies {
	compileInclude group: "io.netty", name: "netty-buffer", version: "4.1.100.Final"
	compileInclude group: "io.netty", name: "netty-codec", version: "4.1.100.Final"
	compileInclude group: "io.netty", name: "netty-codec-http", version: "4.1.100.Final"
	compileInclude group: "io.netty", name: "netty-codec-http2", version: "4.1.100.Final"
	compileInclude group: "io.netty", name: "netty-common", version: "4.1.100.Final"
	compileInclude group: "io.netty", name: "netty-handler", version: "4.1.100.Final"
	compileInclude group: "io.netty", name: "netty-handler-proxy", version: "4.1.100.Final"
	compileInclude group: "io.netty", name: "netty-resolver", version: "4.1.100.Final"
	compileInclude group: "io.netty", name: "netty-resolver-dns", version: "4.1.100.Final"
	compileInclude group: "io.netty", name: "netty-transport", version: "4.1.100.Final"
	compileInclude group: 'io.netty', name: 'netty-buffer', version: '4.1.110.Final'
	compileInclude group: 'io.netty', name: 'netty-codec', version: '4.1.110.Final'
	compileInclude group: 'io.netty', name: 'netty-codec-dns', version: '4.1.109.Final'
	compileInclude group: 'io.netty', name: 'netty-codec-http', version: '4.1.110.Final'
	compileInclude group: 'io.netty', name: 'netty-codec-http2', version: '4.1.110.Final'
	compileInclude group: 'io.netty', name: 'netty-codec-socks', version: '4.1.110.Final'
	compileInclude 	group: 'io.netty', name: 'netty-common', version: '4.1.110.Final'
	compileInclude group: 'io.netty', name: 'netty-handler', version: '4.1.110.Final'
	compileInclude group: 'io.netty', name: 'netty-handler-proxy', version: '4.1.110.Final'
	compileInclude 	group: 'io.netty', name: 'netty-resolver', version: '4.1.110.Final'
	compileInclude 	group: 'io.netty', name: 'netty-resolver-dns', version: '4.1.109.Final'
	compileInclude 	group: 'io.netty', name: 'netty-resolver-dns-classes-macos', version: '4.1.109.Final'
	compileInclude group: 'io.netty', name: 'netty-resolver-dns-native-macos', version: '4.1.109.Final'
	compileInclude 	group: 'io.netty', name: 'netty-tcnative-boringssl-static', version: '2.0.65.Final'
	compileInclude 	group: 'io.netty', name: 'netty-tcnative-classes', version: '2.0.65.Final'
	compileInclude group: 'io.netty', name: 'netty-transport', version: '4.1.110.Final'
	compileInclude 	group: 'io.netty', name: 'netty-transport-classes-epoll', version: '4.1.110.Final'
	compileInclude group: 'io.netty', name: 'netty-transport-classes-kqueue', version: '4.1.110.Final'
	compileInclude group: 'io.netty', name: 'netty-transport-native-epoll', version: '4.1.110.Final'
	compileInclude 	group: 'io.netty', name: 'netty-transport-native-kqueue', version: '4.1.110.Final'
	compileInclude group: 'io.netty', name: 'netty-transport-native-unix-common', version: '4.1.110.Final'
	compileInclude group: 'io.projectreactor', name: 'reactor-core', version: '3.4.38'
	compileInclude group: 'io.projectreactor.netty', name: 'reactor-netty-http', version: '1.0.45'
	compileInclude 	group: 'io.projectreactor.netty', name: 'reactor-netty-core', version: '1.0.45'
	compileInclude group: 'org.reactivestreams', name: 'reactive-streams', version: '1.0.4'
}