dependencies {
	compileInclude group: "com.zaxxer", name: "SparseBitSet", version: "1.2"
	compileInclude group: "org.apache.commons", name: "commons-collections4", version: "4.4"
	compileInclude group: "org.apache.commons", name: "commons-math3", version: "3.6.1"
	compileInclude group: "org.apache.poi", name: "poi", version: "4.1.2"
	compileInclude group: "org.apache.poi", name: "poi-ooxml", version: "4.1.2"
	compileInclude group: "org.apache.poi", name: "poi-ooxml-schemas", version: "4.1.2"
	compileInclude group: "org.apache.poi", name: "poi-scratchpad", version: "4.1.2"
	compileInclude group: "org.apache.xmlbeans", name: "xmlbeans", version: "3.1.0"
}