dependencies {
	compileInclude group: "org.apache.poi", name: "poi", version: "4.1.2"
	compileInclude group: "org.apache.poi", name: "poi-ooxml", version: "4.1.2"
	compileInclude group: "org.apache.poi", name: "poi-ooxml-schemas", version: "4.1.2"
	compileInclude group: "org.apache.poi", name: "poi-scratchpad", version: "4.1.2"
}