/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DateColumnEntry service. Represents a row in the &quot;DateColumnEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.DateColumnEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.DateColumnEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DateColumnEntry
 * @generated
 */
@ProviderType
public interface DateColumnEntryModel extends BaseModel<DateColumnEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a date column entry model instance should use the {@link DateColumnEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this date column entry.
	 *
	 * @return the primary key of this date column entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this date column entry.
	 *
	 * @param primaryKey the primary key of this date column entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the date column entry ID of this date column entry.
	 *
	 * @return the date column entry ID of this date column entry
	 */
	public long getDateColumnEntryId();

	/**
	 * Sets the date column entry ID of this date column entry.
	 *
	 * @param dateColumnEntryId the date column entry ID of this date column entry
	 */
	public void setDateColumnEntryId(long dateColumnEntryId);

	/**
	 * Returns the date value of this date column entry.
	 *
	 * @return the date value of this date column entry
	 */
	public Date getDateValue();

	/**
	 * Sets the date value of this date column entry.
	 *
	 * @param dateValue the date value of this date column entry
	 */
	public void setDateValue(Date dateValue);

	@Override
	public DateColumnEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:2053756430