/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DistinctUserIdEntry service. Represents a row in the &quot;DistinctUserIdEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.DistinctUserIdEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.DistinctUserIdEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DistinctUserIdEntry
 * @generated
 */
@ProviderType
public interface DistinctUserIdEntryModel
	extends BaseModel<DistinctUserIdEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a distinct user ID entry model instance should use the {@link DistinctUserIdEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this distinct user ID entry.
	 *
	 * @return the primary key of this distinct user ID entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this distinct user ID entry.
	 *
	 * @param primaryKey the primary key of this distinct user ID entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the distinct user ID entry ID of this distinct user ID entry.
	 *
	 * @return the distinct user ID entry ID of this distinct user ID entry
	 */
	public long getDistinctUserIdEntryId();

	/**
	 * Sets the distinct user ID entry ID of this distinct user ID entry.
	 *
	 * @param distinctUserIdEntryId the distinct user ID entry ID of this distinct user ID entry
	 */
	public void setDistinctUserIdEntryId(long distinctUserIdEntryId);

	/**
	 * Returns the user ID of this distinct user ID entry.
	 *
	 * @return the user ID of this distinct user ID entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this distinct user ID entry.
	 *
	 * @param userId the user ID of this distinct user ID entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this distinct user ID entry.
	 *
	 * @return the user uuid of this distinct user ID entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this distinct user ID entry.
	 *
	 * @param userUuid the user uuid of this distinct user ID entry
	 */
	public void setUserUuid(String userUuid);

	@Override
	public DistinctUserIdEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:722042767