/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RenamedPKColumnEntry service. Represents a row in the &quot;RenamedPKColumnEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.RenamedPKColumnEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.RenamedPKColumnEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RenamedPKColumnEntry
 * @generated
 */
@ProviderType
public interface RenamedPKColumnEntryModel
	extends BaseModel<RenamedPKColumnEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a renamed pk column entry model instance should use the {@link RenamedPKColumnEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this renamed pk column entry.
	 *
	 * @return the primary key of this renamed pk column entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this renamed pk column entry.
	 *
	 * @param primaryKey the primary key of this renamed pk column entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the renamed pk column entry ID of this renamed pk column entry.
	 *
	 * @return the renamed pk column entry ID of this renamed pk column entry
	 */
	public long getRenamedPKColumnEntryId();

	/**
	 * Sets the renamed pk column entry ID of this renamed pk column entry.
	 *
	 * @param renamedPKColumnEntryId the renamed pk column entry ID of this renamed pk column entry
	 */
	public void setRenamedPKColumnEntryId(long renamedPKColumnEntryId);

	/**
	 * Returns the name of this renamed pk column entry.
	 *
	 * @return the name of this renamed pk column entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this renamed pk column entry.
	 *
	 * @param name the name of this renamed pk column entry
	 */
	public void setName(String name);

	@Override
	public RenamedPKColumnEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:525141683