/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SQLQueryEntry service. Represents a row in the &quot;SQLQueryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.SQLQueryEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.SQLQueryEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SQLQueryEntry
 * @generated
 */
@ProviderType
public interface SQLQueryEntryModel extends BaseModel<SQLQueryEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sql query entry model instance should use the {@link SQLQueryEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this sql query entry.
	 *
	 * @return the primary key of this sql query entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sql query entry.
	 *
	 * @param primaryKey the primary key of this sql query entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sql query entry ID of this sql query entry.
	 *
	 * @return the sql query entry ID of this sql query entry
	 */
	public long getSqlQueryEntryId();

	/**
	 * Sets the sql query entry ID of this sql query entry.
	 *
	 * @param sqlQueryEntryId the sql query entry ID of this sql query entry
	 */
	public void setSqlQueryEntryId(long sqlQueryEntryId);

	/**
	 * Returns the user ID of this sql query entry.
	 *
	 * @return the user ID of this sql query entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this sql query entry.
	 *
	 * @param userId the user ID of this sql query entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sql query entry.
	 *
	 * @return the user uuid of this sql query entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this sql query entry.
	 *
	 * @param userUuid the user uuid of this sql query entry
	 */
	public void setUserUuid(String userUuid);

	@Override
	public SQLQueryEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-234520585