/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.DateEntry;

/**
 * The extended model base implementation for the DateEntry service. Represents a row in the &quot;DateEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DateEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DateEntryImpl
 * @see DateEntry
 * @generated
 */
public abstract class DateEntryBaseImpl
	extends DateEntryModelImpl implements DateEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a date entry model instance should use the <code>DateEntry</code> interface instead.
	 */

}
// LIFERAY-SERVICE-BUILDER-HASH:-904959846