/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.DateColumnEntry;

/**
 * The extended model base implementation for the DateColumnEntry service. Represents a row in the &quot;DateColumnEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DateColumnEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DateColumnEntryImpl
 * @see DateColumnEntry
 * @generated
 */
public abstract class DateColumnEntryBaseImpl
	extends DateColumnEntryModelImpl implements DateColumnEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a date column entry model instance should use the <code>DateColumnEntry</code> interface instead.
	 */

}
// LIFERAY-SERVICE-BUILDER-HASH:-1881180296