/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.DistinctUserIdEntry;
import com.liferay.portal.tools.service.builder.test.model.DistinctUserIdEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DistinctUserIdEntry service. Represents a row in the &quot;DistinctUserIdEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DistinctUserIdEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DistinctUserIdEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DistinctUserIdEntryImpl
 * @generated
 */
public class DistinctUserIdEntryModelImpl
	extends BaseModelImpl<DistinctUserIdEntry>
	implements DistinctUserIdEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a distinct user ID entry model instance should use the <code>DistinctUserIdEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DistinctUserIdEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"distinctUserIdEntryId", Types.BIGINT}, {"userId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("distinctUserIdEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DistinctUserIdEntry (distinctUserIdEntryId LONG not null primary key,userId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table DistinctUserIdEntry";

	public static final String ENTITY_ALIAS = "distinctUserIdEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY distinctUserIdEntry.distinctUserIdEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DistinctUserIdEntry.distinctUserIdEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DISTINCTUSERIDENTRYID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.DistinctUserIdEntry"));

	public DistinctUserIdEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _distinctUserIdEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDistinctUserIdEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _distinctUserIdEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DistinctUserIdEntry.class;
	}

	@Override
	public String getModelClassName() {
		return DistinctUserIdEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DistinctUserIdEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DistinctUserIdEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DistinctUserIdEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DistinctUserIdEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DistinctUserIdEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DistinctUserIdEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DistinctUserIdEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DistinctUserIdEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DistinctUserIdEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DistinctUserIdEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DistinctUserIdEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DistinctUserIdEntry, Object>>();

			attributeGetterFunctions.put(
				"distinctUserIdEntryId",
				DistinctUserIdEntry::getDistinctUserIdEntryId);
			attributeGetterFunctions.put(
				"userId", DistinctUserIdEntry::getUserId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<DistinctUserIdEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DistinctUserIdEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<DistinctUserIdEntry, ?>>();

			attributeSetterBiConsumers.put(
				"distinctUserIdEntryId",
				(BiConsumer<DistinctUserIdEntry, Long>)
					DistinctUserIdEntry::setDistinctUserIdEntryId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<DistinctUserIdEntry, Long>)
					DistinctUserIdEntry::setUserId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getDistinctUserIdEntryId() {
		return _distinctUserIdEntryId;
	}

	@Override
	public void setDistinctUserIdEntryId(long distinctUserIdEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_distinctUserIdEntryId = distinctUserIdEntryId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, DistinctUserIdEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DistinctUserIdEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DistinctUserIdEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DistinctUserIdEntryImpl distinctUserIdEntryImpl =
			new DistinctUserIdEntryImpl();

		distinctUserIdEntryImpl.setDistinctUserIdEntryId(
			getDistinctUserIdEntryId());
		distinctUserIdEntryImpl.setUserId(getUserId());

		distinctUserIdEntryImpl.resetOriginalValues();

		return distinctUserIdEntryImpl;
	}

	@Override
	public DistinctUserIdEntry cloneWithOriginalValues() {
		DistinctUserIdEntryImpl distinctUserIdEntryImpl =
			new DistinctUserIdEntryImpl();

		distinctUserIdEntryImpl.setDistinctUserIdEntryId(
			this.<Long>getColumnOriginalValue("distinctUserIdEntryId"));
		distinctUserIdEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));

		return distinctUserIdEntryImpl;
	}

	@Override
	public int compareTo(DistinctUserIdEntry distinctUserIdEntry) {
		long primaryKey = distinctUserIdEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DistinctUserIdEntry)) {
			return false;
		}

		DistinctUserIdEntry distinctUserIdEntry = (DistinctUserIdEntry)object;

		long primaryKey = distinctUserIdEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DistinctUserIdEntry> toCacheModel() {
		DistinctUserIdEntryCacheModel distinctUserIdEntryCacheModel =
			new DistinctUserIdEntryCacheModel();

		distinctUserIdEntryCacheModel.distinctUserIdEntryId =
			getDistinctUserIdEntryId();

		distinctUserIdEntryCacheModel.userId = getUserId();

		return distinctUserIdEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DistinctUserIdEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DistinctUserIdEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DistinctUserIdEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DistinctUserIdEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DistinctUserIdEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DistinctUserIdEntry.class, ModelWrapper.class);

	}

	private long _distinctUserIdEntryId;
	private long _userId;

	public <T> T getColumnValue(String columnName) {
		Function<DistinctUserIdEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DistinctUserIdEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"distinctUserIdEntryId", _distinctUserIdEntryId);
		_columnOriginalValues.put("userId", _userId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("distinctUserIdEntryId", 1L);

		columnBitmasks.put("userId", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DistinctUserIdEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-181877408