/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.RenamedPKColumnEntry;
import com.liferay.portal.tools.service.builder.test.model.RenamedPKColumnEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RenamedPKColumnEntry service. Represents a row in the &quot;RenamedPKColumnEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RenamedPKColumnEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RenamedPKColumnEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RenamedPKColumnEntryImpl
 * @generated
 */
public class RenamedPKColumnEntryModelImpl
	extends BaseModelImpl<RenamedPKColumnEntry>
	implements RenamedPKColumnEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a renamed pk column entry model instance should use the <code>RenamedPKColumnEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "RenamedPKColumnEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"rPKColumnEntryId", Types.BIGINT}, {"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("rPKColumnEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table RenamedPKColumnEntry (rPKColumnEntryId LONG not null primary key,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table RenamedPKColumnEntry";

	public static final String ENTITY_ALIAS = "renamedPKColumnEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY renamedPKColumnEntry.renamedPKColumnEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY RenamedPKColumnEntry.rPKColumnEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RENAMEDPKCOLUMNENTRYID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.RenamedPKColumnEntry"));

	public RenamedPKColumnEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _renamedPKColumnEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRenamedPKColumnEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _renamedPKColumnEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RenamedPKColumnEntry.class;
	}

	@Override
	public String getModelClassName() {
		return RenamedPKColumnEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RenamedPKColumnEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RenamedPKColumnEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RenamedPKColumnEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RenamedPKColumnEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RenamedPKColumnEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RenamedPKColumnEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RenamedPKColumnEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RenamedPKColumnEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RenamedPKColumnEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<RenamedPKColumnEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<RenamedPKColumnEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<RenamedPKColumnEntry, Object>>();

			attributeGetterFunctions.put(
				"renamedPKColumnEntryId",
				RenamedPKColumnEntry::getRenamedPKColumnEntryId);
			attributeGetterFunctions.put("name", RenamedPKColumnEntry::getName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<RenamedPKColumnEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<RenamedPKColumnEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<RenamedPKColumnEntry, ?>>();

			attributeSetterBiConsumers.put(
				"renamedPKColumnEntryId",
				(BiConsumer<RenamedPKColumnEntry, Long>)
					RenamedPKColumnEntry::setRenamedPKColumnEntryId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<RenamedPKColumnEntry, String>)
					RenamedPKColumnEntry::setName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getRenamedPKColumnEntryId() {
		return _renamedPKColumnEntryId;
	}

	@Override
	public void setRenamedPKColumnEntryId(long renamedPKColumnEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_renamedPKColumnEntryId = renamedPKColumnEntryId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RenamedPKColumnEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RenamedPKColumnEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RenamedPKColumnEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RenamedPKColumnEntryImpl renamedPKColumnEntryImpl =
			new RenamedPKColumnEntryImpl();

		renamedPKColumnEntryImpl.setRenamedPKColumnEntryId(
			getRenamedPKColumnEntryId());
		renamedPKColumnEntryImpl.setName(getName());

		renamedPKColumnEntryImpl.resetOriginalValues();

		return renamedPKColumnEntryImpl;
	}

	@Override
	public RenamedPKColumnEntry cloneWithOriginalValues() {
		RenamedPKColumnEntryImpl renamedPKColumnEntryImpl =
			new RenamedPKColumnEntryImpl();

		renamedPKColumnEntryImpl.setRenamedPKColumnEntryId(
			this.<Long>getColumnOriginalValue("rPKColumnEntryId"));
		renamedPKColumnEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));

		return renamedPKColumnEntryImpl;
	}

	@Override
	public int compareTo(RenamedPKColumnEntry renamedPKColumnEntry) {
		long primaryKey = renamedPKColumnEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RenamedPKColumnEntry)) {
			return false;
		}

		RenamedPKColumnEntry renamedPKColumnEntry =
			(RenamedPKColumnEntry)object;

		long primaryKey = renamedPKColumnEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RenamedPKColumnEntry> toCacheModel() {
		RenamedPKColumnEntryCacheModel renamedPKColumnEntryCacheModel =
			new RenamedPKColumnEntryCacheModel();

		renamedPKColumnEntryCacheModel.renamedPKColumnEntryId =
			getRenamedPKColumnEntryId();

		renamedPKColumnEntryCacheModel.name = getName();

		String name = renamedPKColumnEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			renamedPKColumnEntryCacheModel.name = null;
		}

		return renamedPKColumnEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RenamedPKColumnEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RenamedPKColumnEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RenamedPKColumnEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(RenamedPKColumnEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RenamedPKColumnEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RenamedPKColumnEntry.class, ModelWrapper.class);

	}

	private long _renamedPKColumnEntryId;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RenamedPKColumnEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RenamedPKColumnEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("rPKColumnEntryId", _renamedPKColumnEntryId);
		_columnOriginalValues.put("name", _name);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("rPKColumnEntryId", "renamedPKColumnEntryId");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("rPKColumnEntryId", 1L);

		columnBitmasks.put("name", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RenamedPKColumnEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1305752177