/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.portal.tools.service.builder.test.model.SQLQueryEntry;

/**
 * The extended model base implementation for the SQLQueryEntry service. Represents a row in the &quot;SQLQueryEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SQLQueryEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SQLQueryEntryImpl
 * @see SQLQueryEntry
 * @generated
 */
public abstract class SQLQueryEntryBaseImpl
	extends SQLQueryEntryModelImpl implements SQLQueryEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sql query entry model instance should use the <code>SQLQueryEntry</code> interface instead.
	 */

}
// LIFERAY-SERVICE-BUILDER-HASH:-1243899446